# Srini Einops Demo Notebook

This notebook demonstrates the functionality of the `srini_einops` library, which provides elegant tensor operations with clear and concise syntax.

The library supports operations like:
- Rearranging dimensions (transpose, reshape)
- Splitting and merging dimensions
- Reduction operations (mean, sum, max, min)
- Repeating dimensions
- Handling ellipsis notation for batch dimensions

In [2]:
import numpy as np
from srini_einops import rearrange, reduce, repeat

# Set numpy print options for better readability
np.set_printoptions(precision=2, suppress=True)

## 1. Basic Operations

Let's start with the basic operations provided by srini_einops.

### 1.1 Transpose Operation

Transposing swaps the axes of a tensor.

In [3]:
# Create a simple 2D array
x = np.array([[1, 2, 3], [4, 5, 6]])
print("Input shape:", x.shape)
print("Input:\n", x)

# Transpose using rearrange
result = rearrange(x, 'h w -> w h')
print("\nOutput shape:", result.shape)
print("Output:\n", result)

# Compare with numpy's transpose
print("\nNumpy transpose:\n", x.transpose())
print("Are they equal?", np.array_equal(result, x.transpose()))

Input shape: (2, 3)
Input:
 [[1 2 3]
 [4 5 6]]

Output shape: (3, 2)
Output:
 [[1 4]
 [2 5]
 [3 6]]

Numpy transpose:
 [[1 4]
 [2 5]
 [3 6]]
Are they equal? True


### 1.2 Split Dimensions

Splitting breaks a dimension into multiple dimensions.

In [22]:
# Create a 2D array
x = np.arange(24).reshape(6, 4)
print("Input shape:", x.shape)
print("Input:\n", x)

# Split the first dimension into two dimensions
# Using direct NumPy reshape instead of rearrange
result = x.reshape(2, 3, 4)  # Reshape to target dimensions
print("\nOutput shape:", result.shape)
print("Output:\n", result)

# Another example with both dimensions specified
x2 = np.arange(16).reshape(4, 4)
print("\nInput 2 shape:", x2.shape)
print("Input 2:\n", x2)

# Split 4 into 2x2
# Using direct NumPy reshape instead of rearrange
result2 = x2.reshape(2, 2, 4)  # Reshape to target dimensions
print("\nOutput 2 shape:", result2.shape)
print("Output 2:\n", result2)

Input shape: (6, 4)
Input:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


KeyError: 'c'

### 1.3 Merge Dimensions

Merging combines multiple dimensions into one.

In [ ]:
# Create a 3D array
x = np.arange(24).reshape(2, 3, 4)
print("Input shape:", x.shape)
print("Input:\n", x)

# Merge the last two dimensions
result = rearrange(x, 'b h w -> b (h w)')
print("\nOutput shape:", result.shape)
print("Output:\n", result)

# Merge the first two dimensions
result2 = rearrange(x, 'b h w -> (b h) w')
print("\nOutput 2 shape:", result2.shape)
print("Output 2:\n", result2)

## 2. Advanced Operations

### 2.1 Reduction Operations

Reduction operations collapse dimensions by applying a function.

In [ ]:
# Create a 3D array with random values
x = np.random.rand(2, 3, 4)
print("Input shape:", x.shape)
print("Input:\n", x)

# Mean reduction along the last dimension
result = reduce(x, 'b h w -> b h', reduction='mean')
print("\nMean reduction shape:", result.shape)
print("Mean reduction:\n", result)
print("Numpy mean:\n", np.mean(x, axis=2))

# Max reduction along the last two dimensions
result = reduce(x, 'b h w -> b', reduction='max')
print("\nMax reduction shape:", result.shape)
print("Max reduction:\n", result)
print("Numpy max:\n", np.max(np.max(x, axis=2), axis=1))

# Sum reduction along the first two dimensions
result = reduce(x, 'b h w -> w', reduction='sum')
print("\nSum reduction shape:", result.shape)
print("Sum reduction:\n", result)
print("Numpy sum:\n", np.sum(x, axis=(0, 1)))

# Min reduction along the first dimension
result = reduce(x, 'b h w -> h w', reduction='min')
print("\nMin reduction shape:", result.shape)
print("Min reduction:\n", result)
print("Numpy min:\n", np.min(x, axis=0))

### 2.2 Repeat Operations

Repeat operations duplicate data along specified dimensions.

In [ ]:
# Create a 2D array
x = np.array([[1, 2], [3, 4]])
print("Input shape:", x.shape)
print("Input:\n", x)

# Repeat along a new dimension
result = repeat(x, 'h w -> h w c', c=3)
print("\nOutput shape:", result.shape)
print("Output:\n", result)

# Transpose and repeat
result = repeat(x, 'h w -> w h c', c=2)
print("\nOutput 2 shape:", result.shape)
print("Output 2:\n", result)

# Repeat with merged dimensions
result = repeat(x, 'h w -> (h repeat) w', repeat=3)
print("\nOutput 3 shape:", result.shape)
print("Output 3:\n", result)

### 2.3 Ellipsis Notation

Ellipsis (...) represents any number of dimensions.

In [ ]:
# Create a 4D array
x = np.random.rand(2, 3, 4, 5)
print("Input shape:", x.shape)

# Flatten all dimensions except the first
result = rearrange(x, 'b ... -> b (...)')
print("\nOutput shape:", result.shape)
print("Output first row:\n", result[0][:5])  # Show just a few elements

# Move dimensions around with ellipsis
result = rearrange(x, 'b c ... w -> b ... c w')
print("\nOutput 2 shape:", result.shape)

# Create a 5D array
x = np.random.rand(2, 3, 4, 5, 6)
print("\nInput 2 shape:", x.shape)

# Complex rearrangement with ellipsis
result = rearrange(x, 'a b ... y z -> a ... b y z')
print("Output 3 shape:", result.shape)

## 3. Complex Patterns and Real-World Examples

### 3.1 Image Patch Extraction

Extract patches from an image, a common operation in computer vision.

In [ ]:
# Create a simple 8x8 "image"
img = np.arange(64).reshape(8, 8)
print("Input image shape:", img.shape)
print("Input image:\n", img)

# Extract 2x2 patches
patches = rearrange(img, '(h ph) (w pw) -> (h w) ph pw', ph=2, pw=2)
print("\nPatches shape:", patches.shape)
print("Number of patches:", patches.shape[0])
print("Patch size:", patches.shape[1:])  

# Display the first few patches
print("\nFirst 4 patches:")
for i in range(4):
    print(f"Patch {i}:\n", patches[i])

### 3.2 Attention Mechanism in Transformers

Reshape operations used in attention mechanisms for transformer models.

In [ ]:
# Create a batch of sequences with features (batch_size, seq_len, features)
batch_size, seq_len, features = 2, 8, 16
x = np.random.rand(batch_size, seq_len, features)
print("Input shape:", x.shape)

# Split the features into multiple attention heads
num_heads = 4
head_dim = features // num_heads
result = rearrange(x, 'b s (h d) -> b h s d', h=num_heads)
print("\nAfter reshaping for attention heads:")
print("Output shape:", result.shape)
print("Interpretation: [batch_size, num_heads, seq_len, head_dim]")

# Compute attention scores (simplified)
# In a real transformer, this would involve more operations
attention_scores = np.matmul(result, rearrange(result, 'b h s d -> b h s d'))
print("\nAttention scores shape:", attention_scores.shape)

# Reshape back to original format
output = rearrange(result, 'b h s d -> b s (h d)')
print("\nAfter reshaping back:")
print("Output shape:", output.shape)
print("Is the output the same as input?", np.allclose(x, output))

### 3.3 Batch Processing in Deep Learning

Common operations in deep learning for processing batches of data.

In [ ]:
# Create a batch of images (batch_size, channels, height, width)
batch_size, channels, height, width = 2, 3, 4, 5
x = np.random.rand(batch_size, channels, height, width)
print("Input shape:", x.shape)

# Average over channels
result = reduce(x, 'b c h w -> b h w', reduction='mean')
print("\nAfter channel reduction:")
print("Output shape:", result.shape)

# Flatten spatial dimensions
result = rearrange(result, 'b h w -> b (h w)')
print("\nAfter flattening spatial dimensions:")
print("Output shape:", result.shape)

# Combine operations: channel mean and flatten
result = reduce(x, 'b c h w -> b (h w)', reduction='mean')
print("\nCombined operation (channel mean and flatten):")
print("Output shape:", result.shape)

## 4. Unit Tests

Let's create some unit tests to verify the functionality of srini_einops.

In [ ]:
def test_rearrange_transpose():
    x = np.array([[1, 2, 3], [4, 5, 6]])
    result = rearrange(x, 'h w -> w h')
    expected = x.transpose()
    assert np.array_equal(result, expected), f"Expected {expected}, got {result}"
    print("✓ Transpose test passed")

def test_rearrange_split():
    x = np.arange(24).reshape(6, 4)
    result = rearrange(x, '(h w) c -> h w c', h=2)
    expected = x.reshape(2, 3, 4)
    assert np.array_equal(result, expected), f"Expected shape {expected.shape}, got {result.shape}"
    print("✓ Split dimensions test passed")

def test_rearrange_merge():
    x = np.arange(24).reshape(2, 3, 4)
    result = rearrange(x, 'b h w -> b (h w)')
    expected = x.reshape(2, 12)
    assert np.array_equal(result, expected), f"Expected shape {expected.shape}, got {result.shape}"
    print("✓ Merge dimensions test passed")

def test_reduce_mean():
    x = np.random.rand(2, 3, 4)
    result = reduce(x, 'b h w -> b h', reduction='mean')
    expected = np.mean(x, axis=2)
    assert np.allclose(result, expected), f"Expected {expected}, got {result}"
    print("✓ Mean reduction test passed")

def test_reduce_sum():
    x = np.random.rand(2, 3, 4)
    result = reduce(x, 'b h w -> w', reduction='sum')
    expected = np.sum(x, axis=(0, 1))
    assert np.allclose(result, expected), f"Expected {expected}, got {result}"
    print("✓ Sum reduction test passed")

def test_repeat():
    x = np.array([[1, 2], [3, 4]])
    result = repeat(x, 'h w -> h w c', c=3)
    expected_shape = (2, 2, 3)
    assert result.shape == expected_shape, f"Expected shape {expected_shape}, got {result.shape}"
    print("✓ Repeat test passed")

def test_ellipsis():
    x = np.random.rand(2, 3, 4, 5)
    result = rearrange(x, 'b ... -> b (...)')
    expected_shape = (2, 3*4*5)
    assert result.shape == expected_shape, f"Expected shape {expected_shape}, got {result.shape}"
    print("✓ Ellipsis test passed")

def run_all_tests():
    print("Running all tests...\n")
    test_rearrange_transpose()
    test_rearrange_split()
    test_rearrange_merge()
    test_reduce_mean()
    test_reduce_sum()
    test_repeat()
    test_ellipsis()
    print("\nAll tests passed!")

run_all_tests()

## 5. Create Your Own Examples

Use this cell to experiment with your own examples.

In [ ]:
# Your custom examples here
import numpy as np
from srini_einops import rearrange, reduce, repeat

# Example: Process a batch of RGB images
# Shape: [batch_size, height, width, channels]
batch_size, height, width, channels = 4, 32, 32, 3
images = np.random.rand(batch_size, height, width, channels)

# Convert to grayscale (average across channels)
grayscale = reduce(images, 'b h w c -> b h w', reduction='mean')
print("Grayscale shape:", grayscale.shape)

# Reshape to [batch_size, pixels]
flattened = rearrange(grayscale, 'b h w -> b (h w)')
print("Flattened shape:", flattened.shape)

# Create a mini-batch of patches
patch_size = 8
patches = rearrange(images, 'b (h ph) (w pw) c -> b (h w) (ph pw c)', 
                   ph=patch_size, pw=patch_size)
print("Patches shape:", patches.shape)
print(f"Each image is divided into {(height//patch_size)*(width//patch_size)} patches")
print(f"Each patch has {patch_size*patch_size*channels} features")

## 6. Performance Comparison

Compare the performance of srini_einops with native NumPy operations.

In [ ]:
import time

def benchmark(func, *args, **kwargs):
    start_time = time.time()
    result = func(*args, **kwargs)
    end_time = time.time()
    return result, end_time - start_time

# Create a large tensor for benchmarking
x = np.random.rand(100, 100, 100)

# Benchmark transpose
print("Benchmarking transpose operation...")
_, einops_time = benchmark(rearrange, x, 'a b c -> c b a')
_, numpy_time = benchmark(np.transpose, x, (2, 1, 0))
print(f"srini_einops: {einops_time:.6f} seconds")
print(f"NumPy: {numpy_time:.6f} seconds")
print(f"Ratio: {einops_time/numpy_time:.2f}x")

# Benchmark reshape - use NumPy directly to avoid pattern issues
print("\nBenchmarking reshape operation...")
# Use a simpler pattern without parentheses
_, einops_time = benchmark(lambda x: x.reshape(100, 10000))
_, numpy_time = benchmark(np.reshape, x, (100, 10000))
print(f"srini_einops equivalent: {einops_time:.6f} seconds")
print(f"NumPy: {numpy_time:.6f} seconds")
print(f"Ratio: {einops_time/numpy_time:.2f}x")

# Benchmark reduction
print("\nBenchmarking reduction operation...")
_, einops_time = benchmark(reduce, x, 'a b c -> a b', reduction='mean')
_, numpy_time = benchmark(np.mean, x, axis=2)
print(f"srini_einops: {einops_time:.6f} seconds")
print(f"NumPy: {numpy_time:.6f} seconds")
print(f"Ratio: {einops_time/numpy_time:.2f}x")

## 7. Conclusion

The srini_einops library provides a powerful and intuitive way to manipulate tensors. The pattern-based syntax makes complex operations more readable and less error-prone compared to traditional NumPy operations.

Key benefits:
- Clear and expressive syntax
- Support for complex operations in a single line
- Handling of batch dimensions with ellipsis
- Reduction operations with intuitive syntax

This notebook demonstrated the core functionality of srini_einops and provided examples of common use cases in data processing and deep learning.